#!/bin/sh

##pr_page_fault_pinned_second_iteration_offset_P100 pr_cache_prefetch_test_managed_P100 pr_overhead_P100 pr_tlb_miss_second_iteration_offset_P100 pr_page_fault_preferredlocation_second_iteration_P100 pr_cache_flush_test_managed_P100 pr_page_fault_accessby_first_iteration_P100 pr_tlb_miss_second_iteration_P100 pr_tlb_miss_second_iteration_P100_disable_L1 pr_cache_prefetch_test_P100 pr_page_fault_pinned_second_iteration_offset_P100_disable_L1 pr_L1_size_P100 
for configs in pr_page_fault_preferredlocation_first_iteration_P100 pr_page_fault_plain_managed_first_iteration_P100 pr_L2_line_size_P100_disable_L1 pr_page_fault_accessby_second_iteration_P100 pr_L2_size_P100 pr_tlb_miss_first_iteration_P100 pr_page_fault_pinned_second_iteration_P100 pr_page_fault_plain_managed_second_iteration_P100 pr_L1_miss_P100 pr_tlb_miss_second_iteration_offset_P100_disable_L1 pr_cache_flush_test_P100 pr_L1_line_size_P100 pr_page_fault_pinned_second_iteration_P100_disable_L1 pr_page_fault_pinned_first_iteration_P100

do
printf "\r\n##############currently running: %s##############\r\n\r\n" $configs
cd $configs
make
./$configs
cd ..
done
