#!/bin/sh


for configs in cache_flush_test cache_hit_and_prefetch_validation cache_hit_and_prefetch_validation_2 cache_line_size_validation_L1_only cache_line_size_validation_L2_only cache_prefetch_validation cache_prefetch_validation_disable_L1 cache_prefetch_validation_enable_L1 L1_saturated L1_saturated_K40 L1_size_test L2_prefetch_test_disable_L1 L2_prefetch_test_enable_L1 L2_prefetch_test_enable_L1_old L2_saturated L2_saturated_K40 L2_size_test_disable_L1 L2_size_test_disable_L1_byte L2_size_test_K40_disable_L1 L2_size_test_K40_disable_L1_2 L2_size_test_K40_enable_L1 measurement_overhead_test measurement_overhead_test_per_request memcopy_prefecthing_validation per_request_method_test tlb_hit_and_prefetch_validation tlb_miss_memcopy

do
cd $configs
cp ../Makefile .
cd ..
done
